services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data
  app:
    build: .
    environment:
      DATABASE_URL: postgresql+psycopg://app:app@db:5432/app
      ENV: development
    ports: ["8000:8000"]
    depends_on: ["db"]
    command: bash -lc "poetry run uvicorn app.api.main:app --host 0.0.0.0 --port 8000 --reload"
volumes:
  pgdata:
